language: python

dist: xenial

python:
  - '3.7'

env: TRAVIS=true

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  # This is where you put any extra dependencies you may have.
  - ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock ipython
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda install --yes -c conda-forge python-graphviz emg3d discretize pyvista!=0.25.0 discretize
  - conda install gdal
  - conda install -c anaconda libffi
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install sphinx-gallery
  - pip install qgrid
  - pip install nbval
  - pip install pyevtk
  - pip install arviz
  - pip install recommonmark
  - pip install dataclasses panel
  - pip install welly
  - pip install ipywidgets
  - export PATH="./bin:$PATH"

script:
  - pytest -v notebooks/ --nbval-lax
  - pytest

stages:
  - test
  - deploy

jobs:
  include:
      - stage: test
        script:
          - pytest
      - stage: deploy
        name: Deploy to GitHub Pages
       # if: (NOT type IN (pull_request)) AND (branch = sphinx-gallery) # only deploy if merging on master

        before_script:
         - pip install -e .
         - cd docs
        script: pipenv run make html
        deploy:
          provider: pages # deploy on github pages
          skip_cleanup: true
          github_token: $travis_doc # defined via the Travis interface
          local_dir: docs/build/html
          on:
            branch: docs-devs
          target_branch: gh-pages
          fqdn: docs.gempy.org
cache: pip

